### ISSUE TITLE
HIGH: Issues with Screen Refresh on Scorecard 

### ISSUE THREAD

**Issue by Dannal2017** [Jcros214/QuizSite#22]
Screen would sometimes refresh and just keep refreshing/flashing not allowing scorekeeper to input answers.

Also validation would sometimes clear before the quiz could be submitted.

**Comment by Jcros214** [comment]
Use ajax call instead of page reload

**Comment by Jcros214** [comment]
This was caused by code that was supposed to refresh whenever a scorekeeper updated something, but ended up refreshing the page on every page load, causing a loop.
